Event model
Peer-Lab/mk42 pull request #1
Opened 2017-07-03 17:56 UTC by holdbar

Added Event Model with serializers, viewsets, permissions and admin.

2017-07-04 09:02 UTC, vint21h requested changes
Что у видел то и написал в комментах

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/models/event.py
> +    start = models.DateTimeField(verbose_name=_("start date/time"), blank=True, null=True, db_index=True)
Поле start не может быть пустым

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/models/event.py
> +
group и start было бы неплохо сделать уникальными вместе чтобы не создавались одинаковые события

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/viewsets/event.py
> +from mk42.constants import GET
Лишний import

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/viewsets/event.py
> +from mk42.apps.core.models.membership import Membership
Лишний import

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/viewsets/event.py
> +from rest_framework.response import Response
Лишний import

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/viewsets/event.py
> +from rest_framework.decorators import list_route
Лишний import

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/permissions/event.py
> +        if request.method == DELETE:
А почему нельзя удалять?
Я думаю за час или за день удалять события можно.
Если реализовывать с промежутком времени когда удалять нельзы то вынести эту дельту в constance. См. документацию django-constance, я все настроил см. использование.

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +    list_display = ["id", "name", "description", "group", "start", "created", "updated", ]
description - это большой текст, все поплывет, нужно убрать

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +    list_filter = ["group", "created", "start" ]
В list_filter лучше не использовать поля типа Date/DateTime, при большом количестве записей будут тормоза

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +    search_fields = ["id", "name", "start" ]
Никто не ищет по датам, лучше убрать start и добавить description

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +        [None, {"fields": ["name", "description", "group",], }, ],
А start похоже потерялся

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/api/permissions/event.py
> +        if obj.owner == request.user:
obj здесь это событие, не помню у него поля owner, obj.group.owner есть а owner не помню

2017-07-04 09:02 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +class EventAdmin(admin.ModelAdmin):
Этот клас еще нужно зарегистрировать в __init__.py рядом

2017-07-04 11:59 UTC, holdbar commented on mk42/apps/core/models/event.py
> +
Не совсем понял данный момент. Ты говоришь о том, что у одной группы не может быть несколько событий на одно время?

2017-07-04 12:00 UTC, vint21h commented on mk42/apps/core/models/event.py
> +
+

2017-07-04 12:03 UTC, holdbar commented on mk42/apps/core/api/permissions/event.py
> +        if request.method == DELETE:
А какой смысл их удалять тем более за час или за день? Если из-за того что событие отменено по какой то причине, то удалить его за час это некорректно. Да и вообще в таком случае лучше добавить событиям статус, который при необходимости может быть изменен на "Отменено", с сопутствующей рассылкой уведомлений об отмене. 
Удалять же состоявшиеся события смысла точно не вижу. История, динамика посещений и т.д.

2017-07-04 12:18 UTC, vint21h commented on mk42/apps/core/api/permissions/event.py
> +        if request.method == DELETE:
Состоявшиеся точно удалять нельзя. А со статусами, если хочешь пиши.

2017-07-04 20:06 UTC, vint21h requested changes
Еще неплохо после большого набора изменений отдельным коммитом собирать строки помеченные для перевода "make makemessages" и компилировать их "make compilemessages".

2017-07-04 20:06 UTC, vint21h commented on mk42/apps/core/admin/event.py
> +        [None, {"fields": ["name", "description", "group", "start"], }, ],
address забыт, и в сериализатоеы тоже и миграция нужна под это дело, а вообще неплохо было бы выделить сущность типа location с адресом и координатами, но это на кого-нибудь другого спихнем.

2017-07-05 06:27 UTC, merged

2017-07-05 06:35 UTC, vint21h commented
Глянь что я еще коммитил, и в AUTHORS добавься