Add send email for group model. First try
Peer-Lab/mk42 pull request #13
Opened 2017-07-19 12:51 UTC by edbutcher

2017-07-19 17:44 UTC, vint21h requested changes

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/models/group.py
> +    def email_context(self):
И зачем это здесь?

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/models/group.py
> +    def send_email(self, template, context):
И зачем это здесь?

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "Welcome to" %} {{ site.name }}!
Заче приветствовать?

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "You, or somebody else create group" %} {{ group.name }}
Где создал?

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +                {% trans "You, or somebody else create at" %} <a href="{{ protocol }}//{{ site.domain }}">{{ site.name }}</a> {% trans "group" %} {{ group.name }}
Я что-то не п.

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +                {% trans "Enjoy working on" %} <a href="{{ protocol }}//{{ site.domain }}">{{ site.name }}</a>.
Не нужно.

2017-07-19 17:44 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "Enjoy working on" %} {{ protocol }}//{{ site.domain }}
Не нужно.

2017-07-19 19:26 UTC, edbutcher commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "You, or somebody else create group" %} {{ group.name }}
"group": Group.objects.get_current() - Это так не работает?

2017-07-19 19:27 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "You, or somebody else create group" %} {{ group.name }}
Конечно нет. И причем здесь это?

2017-07-19 19:51 UTC, vint21h requested changes
dump.rdb - а это что?

2017-07-19 19:51 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +    {% trans "You, or somebody else create group" %}
Какую?

2017-07-19 19:51 UTC, vint21h commented on mk42/apps/core/templates/templated_email/group_registration.email
> +                {% trans "You, or somebody else create group at" %} <a href="{{ protocol }}//{{ site.domain }}">{{ site.name }}</a>
Текст в plain и html должен максимально совпадать.

2017-07-19 19:51 UTC, vint21h commented on mk42/apps/core/models/group.py
> +        self.send_email("group_registration", {})
Это не работает.

2017-07-19 20:30 UTC, vint21h commented on mk42/apps/core/models/group.py
> +        self.send_email("group_registration", {})
self.owner.send_email("group_registration", {"group": self, })

2017-07-20 16:58 UTC, vint21h requested changes

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +{% block subject %}{% trans "Registration on" %} - {{ protocol }}//{{ site.domain }}{% endblock %}
{% block subject %}{% trans "Group creation at" %} {{ protocol }}//{{ site.domain }}{% endblock %}

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +    {% trans "You, or somebody else create group" %} {{ group.name }}
{% trans "You, or somebody else create group" %} {{ group.name }} {% trans "at" %} {{ protocol }}//{{ site.domain }}

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +                {% trans "Welcome to" %} {{ site.name }}!
{% trans "Hello!" %}

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +                {% trans "You, or somebody else create group at" %} {{ group.name }}
{% trans "You, or somebody else create group" %} {{ group.name }} {% trans "at" %} <a href="{{ protocol }}//{{ site.domain }}">{{ protocol }}//{{ site.domain }}</a>

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +    {% trans "You, or somebody else create group" %} {{ group.name }}
{% trans "If you do not do this please inform us." %}

2017-07-20 16:58 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +                {% trans "You, or somebody else create group at" %} {{ group.name }}
{% trans "If you do not do this please inform us." %}

2017-07-21 11:33 UTC, vint21h requested changes

2017-07-21 11:33 UTC, vint21h commented on mk42/apps/core/templates/templated_email/create_group_email.email
> +                {% trans "You, or somebody else create group" %} {{ group.name }} {% trans "at" %} {{ protocol }}//{{ site.domain }}
А ссылка где потерялась?

2017-07-21 12:59 UTC, merged