Add event log.
Peer-Lab/mk42 pull request #19
Opened 2017-08-15 15:40 UTC by holdbar

2017-08-15 23:33 UTC, vint21h requested changes
Напоминаю в воскресенье меня не будет

2017-08-15 23:33 UTC, vint21h commented on mk42/apps/core/api/permissions/log.py
> +    	"""
I see dead peoples^W^W useless spaces or tabs

2017-08-15 23:33 UTC, vint21h commented on mk42/apps/core/api/routers.py
> +router.register(r"eventlog", EventLogViewSet)
Может просто log?

2017-08-15 23:33 UTC, vint21h commented on mk42/apps/core/api/routers.py
> +router.register(r"eventlog", EventLogViewSet)
Или через "-"

2017-08-16 03:47 UTC, holdbar commented on mk42/apps/core/api/permissions/log.py
> +    	"""
Work work. I can do that.

2017-08-26 00:32 UTC, merged