i18n
Peer-Lab/mk42 pull request #20
Opened 2017-08-27 17:48 UTC by psychomonkey911

2017-08-31 08:31 UTC, psychomonkey911 commented
прием/прием

2017-08-31 08:55 UTC, sergiosiniy commented
Привет

2017-08-31 11:31 GMT+03:00 psychomonkey911 <notifications@github.com>:

> прием/прием
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Peer-Lab/mk42/pull/20#issuecomment-326227957>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ALhoyflX1m3v__9jJUH52Iu-CK5AlL6Nks5sdm9NgaJpZM4PD3iT>
> .
>

2017-09-01 00:49 UTC, vint21h requested changes
Строки не нужно помечать юникодными, они автоматом уже юникодные.

2017-09-01 00:49 UTC, vint21h commented on mk42/apps/core/urls/api.py
> +    url(r'^i18n/', include('django.conf.urls.i18n')),
Зачем это здесь?

2017-09-01 00:49 UTC, vint21h commented on mk42/apps/core/urls/api.py
> +
Зачем тут пустая строка?

2017-09-01 00:49 UTC, vint21h commented on mk42/settings/common.py
> +    "localeurl",
Это здесь не нужно, и все равно не работало бы.

2017-09-01 00:49 UTC, vint21h commented on mk42/settings/common.py
> +    ("ru", "Русский")
Нахуй не нужен.

2017-09-01 00:49 UTC, vint21h commented on mk42/settings/common.py
> +LOCALE_PATHS = (os.path.join(BASE_DIR, NAME, "locale").replace("\\", "/"),)
Зачем портить кодстайл?

2017-09-01 00:49 UTC, vint21h commented on mk42/settings/common.py
> +STATICFILES_DIRS = (os.path.join(BASE_DIR, NAME, "static").replace("\\", "/"),)
Зачем портить кодстайл?

2017-09-01 00:49 UTC, vint21h commented on mk42/views/base.py
> -
Зачем портить кодстайл?

2017-09-01 00:49 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "член"
Вот ни разу не смешно

2017-09-01 00:49 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "оновленна дата/час"
Ну в контекст же смотреть нужно, "дата/час оновлення"

2017-09-01 14:28 UTC, vint21h requested changes
Убери u перед строками, это не нужно.

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "Другие"
Інше

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "назва" #или имя?
назва

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "slug"
Слаг кстати уже устоявшийся термин

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
>  msgid "overwrite in creation"
Тут я тупанул, в коде модели поменяй на "overwrites during creation"

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
>  msgid "overwrite in creation"
Ну и в переводах пофиксь

2017-09-01 14:28 UTC, vint21h commented on mk42/apps/core/locale/uk/LC_MESSAGES/django.po
> +msgstr "активувати"
Ну смотри же в контекст, тут просто существительное

2017-09-05 18:26 UTC, closed without merging