Add membership approvement by group owner
Peer-Lab/mk42 pull request #5
Opened 2017-07-17 17:02 UTC by holdbar

2017-07-17 17:15 UTC, vint21h requested changes

2017-07-17 17:15 UTC, vint21h commented on mk42/apps/core/models/membership.py
> +    approved = models.BooleanField(verbose_name=_("approved"), db_index=True, default=False)
По-моему название "active" более универсальное.
И еще неплохо написать метод менеджера который бы возвращал только активные membership'ы. И еще дополнительный endpoint в viewset'е.

2017-07-17 17:15 UTC, vint21h commented on mk42/apps/core/api/permissions/membership.py
> +        if all([request.method == PATCH, request.user == obj.group.owner]):
Вот только не задача, сюда мы не попадем.

2017-07-18 06:59 UTC, holdbar commented on mk42/apps/core/api/permissions/membership.py
> +        if all([request.method == PATCH, request.user == obj.group.owner]):
Я так понял нужно добавить обработку PATCH в has_permission?

2017-07-18 07:25 UTC, vint21h commented
+

On Tue, Jul 18, 2017 at 9:59 AM, holdbar <notifications@github.com> wrote:

> *@holdbar* commented on this pull request.
> ------------------------------
>
> In mk42/apps/core/api/permissions/membership.py
> <https://github.com/Peer-Lab/mk42/pull/5#discussion_r127895395>:
>
> > @@ -69,6 +71,10 @@ def has_object_permission(self, request, view, obj):
>              # Allow only delete membership.
>              return True
>
> +        if all([request.method == PATCH, request.user == obj.group.owner]):
>
> Я так понял нужно добавить обработку PATCH в has_permission?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Peer-Lab/mk42/pull/5#discussion_r127895395>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA2ooX0MEWNhwJjZhcWHzs_dxb9KKnM7ks5sPFfBgaJpZM4OaQoA>
> .
>

2017-07-18 08:21 UTC, vint21h requested changes
Раз уж есть endpoint "active" то можно сделать и "inactive".

2017-07-18 10:33 UTC, vint21h requested changes
Кстати, если хочешь можешь сделать "inactive" и для Group.

2017-07-18 10:33 UTC, vint21h commented on mk42/apps/core/api/permissions/membership.py
>              # In futures steps of flow allow user delete own membership.
Думаю что анонимуса надо еще здесь отсекать.

2017-07-18 10:33 UTC, vint21h commented on mk42/apps/core/api/permissions/membership.py
> +        if request.method == PATCH:
Думаю что анонимуса надо еще здесь отсекать.

2017-07-18 10:33 UTC, vint21h commented on mk42/apps/core/querysets/membership.py
> +        return self.filter(active=False)
Еще один виндузятник.

2017-07-18 10:33 UTC, vint21h commented on mk42/apps/core/api/viewsets/group.py
> +        Return only user ownership.
Return only user owned groups.

2017-07-18 10:38 UTC, holdbar commented on mk42/apps/core/querysets/membership.py
> +        return self.filter(active=False)
Увы, на текущей работе нет выбора.

2017-07-18 10:42 UTC, vint21h commented on mk42/apps/core/querysets/membership.py
> +        return self.filter(active=False)
Это не подколка или какое-то обвинение, юзайте кто-что хочет, просто стандарты соблюдайте, да и так конец файла не только софтом определяется, но и визуально отбивается.

2017-07-18 11:41 UTC, holdbar commented on mk42/apps/core/querysets/membership.py
> +        return self.filter(active=False)
Принято.

2017-07-18 13:58 UTC, merged